version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  variable-payload:
    lang: python3-fastapi-debian
    handler: ./variable-payload
    image: ttl.sh/variable-payload:latest

